In [33]:
import pandas as pd
import numpy as np

## Q1

In [3]:
pd.__version__

'3.0.5'

In [5]:
data_file = "..\\data\\car_fuel_efficiency_2026.csv"

In [6]:
df = pd.read_csv(data_file)
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
model_year,10000.0,1999.549500,14.207925,1975.0,1987.0,2000.0,2012.0,2024.0
num_doors,10000.0,3.504000,0.952090,2.0,3.0,4.0,4.0,5.0
engine_displacement,10000.0,2268.807000,183.447355,1590.0,2150.0,2270.0,2390.0,3110.0
num_cylinders,10000.0,6.035200,0.542578,4.0,6.0,6.0,6.0,8.0
horsepower,9123.0,254.446016,22.844613,171.0,239.0,254.0,270.0,334.0
vehicle_weight,10000.0,4286.754000,266.212491,3320.0,4110.0,4280.0,4470.0,5460.0
acceleration,9736.0,18.888044,1.279543,14.0,18.0,18.9,19.7,23.8
fuel_efficiency_mpg,10000.0,29.997700,2.930245,19.8,28.0,30.0,31.9,41.2

## Q2

In [8]:
df.shape[0]

10000

## Q3

In [9]:
df.fuel_type.value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

## Q4

In [12]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5

In [15]:
df.loc[df["origin"] == "Asia", ["fuel_efficiency_mpg"]].max()

fuel_efficiency_mpg    41.2
dtype: float64

## Q6

In [27]:
hp_medium = df["horsepower"].median()
hp_fr = df["horsepower"].value_counts().idxmax()

hp_medium_new = df["horsepower"].fillna(hp_fr).median()

print(f"Median horsepower before filling missing values: {hp_medium}")
print(f"Median horsepower after filling missing values: {hp_medium_new}")

Median horsepower before filling missing values: 254.0
Median horsepower after filling missing values: 252.0

## Q7

In [34]:
X = df.loc[df["origin"] == "Asia", ["vehicle_weight", "model_year"]][:7].to_numpy()

In [35]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [40]:
XTX = X.T @ X
XTX_inv = np.linalg.inv(XTX)

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

w = XTX_inv @ X.T @ y

In [41]:
sum(w)

np.float64(0.36919696904925486)